### ISSUE TITLE
Add ReadMe to Reference Points and Projections

### ISSUE THREAD

**Issue by JDeroba** [NEFSC/READ-PDB-COLLABORATIONS#9]
@CHodgdon1 and @emilyliljestrand I think you two are entirely responsible for the code in the Reference Points and Projections Folder. Can you add a ReadMe to this folder, similar to the one in the WHAM folder please? Shouldn't take long. You can copy and past the WHAM folder ReadMe as a start and just fill-in accordingly.

**Comment by emilyliljestrand** [comment]
Pull request #10
